#!/bin/bash
. `dirname $0`/n2n.config

int_handler (){
  echo ERROR: Exiting on interupt
  edge_is_running && echo WARNING: edge is running
  exit 1
}
trap int_handler INT

if edge_is_running ; then
  if [ "x$1" == 'x-r' ] ; then
    echo 'Killing edge process'
    sudo -p 'I need sudo privs to kill the edge current edge process.
Password:' kill `edge_pid`
  fi
fi

if edge_is_running ; then
  echo "Our edge process (`edge_pid`) for $N2N_COMMUNITY's n2n is running."
  exit 0
else
  echo "Starting edge in the n2n of $N2N_COMMUNITY (supernode: $N2N_SUPERNODE)"
  sudo -p 'I need sudo privs to start the edge.
Password: ' \
    env N2N_KEY=$N2N_PASSWORD \
    edge -c $N2N_COMMUNITY -l $N2N_SUPERNODE -a $N2N_NET.$N2N_ME -r
#-m $N2N_FAKE_MAC
fi

echo -n waiting for ping
for i in a b c d e f ; do
  ping_gateway && break
  sleep 2
  echo -n '.'
done

if ping_gateway ; 
then echo ''; echo ok
else echo "Sorry, can't ping the other gateway" ; exit 1; fi

